#ifndef MODEL_LOADER_DECLARATIONS_H
#define MODEL_LOADER_DECLARATIONS_H

#include <string>

#define MODEL_FORMAT_VERSION_NUMBER 7
#define RIGID_ANIMATION_FORMAT_VERSION_NUMBER 0
#define SKELETAL_ANIMATION_FORMAT_VERSION_NUMBER 1
#define ARMATURE_FORMAT_VERSION_NUMBER 1

#define ANIMATION_TYPE_STRING_RIGID "RIGID"
#define ANIMATION_TYPE_STRING_BAKED_SKELETAL "BAKED_SKELETAL"

#endif // MODEL_LOADER_DECLARATIONS_H
