#ifndef UNIT_ANIMATIONS_DEFINITIONS_H
#define UNIT_ANIMATIONS_DEFINITIONS_H

#define UNIT_ANIMATION_CLIP_NAME_idle "idle"
#define UNIT_ANIMATION_CLIP_NAME_walking "walking"
#define UNIT_ANIMATION_CLIP_NAME_doingspecial "special"

#endif // UNIT_ANIMATIONS_DEFINITIONS_H
