#ifndef MODEL_LOADER_DECLARATIONS_H
#define MODEL_LOADER_DECLARATIONS_H

#include <string>

#define MODEL_FORMAT_VERSION_NUMBER 6
#define ANIMATION_FORMAT_VERSION_NUMBER 0
#define ARMATURE_FORMAT_VERSION_NUMBER 1

#define ANIMATION_TYPE_STRING_RIGID "RIGID"
#define ANIMATION_TYPE_STRING_SKINNED "SKINNED"

#endif // MODEL_LOADER_DECLARATIONS_H
