//
//  ComponentTypeIds.h
//  Created by Matt Kaufmann on 12/11/13.
//

#ifndef EX_COMPONENTTYPEIDS_H
#define EX_COMPONENTTYPEIDS_H

#include "Vajra/Engine/Components/ComponentTypes/ComponentTypeIds.h"

enum ExComponentIdType {
	COMPONENT_TYPE_ID_GRID_MANAGER = NUM_ENGINE_COMPONENT_TYPES,
	COMPONENT_TYPE_ID_GRID_NAVIGATOR,
	COMPONENT_TYPE_ID_GRID_ZONE,
	//
	COMPONENT_TYPE_ID_BASE_UNIT, 
	COMPONENT_TYPE_ID_UNIT_ANIMATION_MANAGER,
	COMPONENT_TYPE_ID_UNIT_SHADOW,
	COMPONENT_TYPE_ID_SAMPLE_GAME_SCRIPT,
	//
	COMPONENT_TYPE_ID_LEVEL_MANAGER,
	COMPONENT_TYPE_ID_MENU_MANAGER,
	COMPONENT_TYPE_ID_MASTERY_MANAGER,
	//
	COMPONENT_TYPE_ID_AI_KNOWLEDGE,
	COMPONENT_TYPE_ID_AI_PERCEPTION,
	COMPONENT_TYPE_ID_AI_ROUTINE,
	//
	COMPONENT_TYPE_ID_BASE_SWITCH,
	COMPONENT_TYPE_ID_TRIGGERABLE,
	//
	COMPONENT_TYPE_ID_DECAL,
};

#endif // EX_COMPONENTTYPEIDS_H
