#ifndef ASSET_LIBRARY_DECLARATIONS_H
#define ASSET_LIBRARY_DECLARATIONS_H

enum AssetType {
	ASSET_TYPE_GENERIC,
	//
	ASSET_TYPE_GL_TEXTURE,
	ASSET_TYPE_MESH_DATA,
	ASSET_TYPE_SOUND_DATA,
	ASSET_TYPE_ANIMATION_DATA,
	//
	NUM_ASSET_TYPES
};

#endif // ASSET_LIBRARY_DECLARATIONS_H
