#ifndef PARTICLE_SYSTEMS_DEFINITIONS_H
#define PARTICLE_SYSTEMS_DEFINITIONS_H

enum EmissionVolumeType_t {
	EMISSION_VOLUME_TYPE_POINT,
	EMISSION_VOLUME_TYPE_CIRCLE_SURFACE,
	EMISSION_VOLUME_TYPE_CIRCLE_CIRCLE,
	EMISSION_VOLUME_TYPE_CIRCLE_CIRCLE_OUTWARD,
	EMISSION_VOLUME_TYPE_ELLIPSOID,
	EMISSION_VOLUME_TYPE_SQUARE,
};

#endif // PARTICLE_SYSTEMS_DEFINITIONS_H
